# WebDWS Backend Application Configuration
# This configuration file defines the application settings for the XML document management backend

# Server Configuration
server:
  port: 8080

# Spring Boot Application Configuration
spring:
  application:
    name: webdws-backend
  
  profiles:
    active: test
  
  # Database Configuration - PostgreSQL for metadata storage
  datasource:
    url: jdbc:postgresql://postgres:5432/webdws
    username: webdws
    password: webdws
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# eXist-db Configuration - XML database for document storage
exist:
  db:
    url: ${EXIST_DB_URL:http://localhost:8081}
    username: ${EXIST_DB_USER:admin}
    password: ${EXIST_DB_PASSWORD:}
    collection: /db/webdws

# Logging Configuration
logging:
  level:
    com.webdws: DEBUG
    org.springframework.web: DEBUG
    org.exist: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration - Health checks and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
